import {
  Actor,
  Casting,
  Project,
  ScriptRole,
  ScriptSkeletonAct,
  Stats,
  ToolDefinition,
} from './gameTypes';

export const project: Project = {
  id: 'divorce-night-gu-family',
  title: '离婚夜，顾总当众强吻我后，白月光也疯了',
  logline:
    '离开顾家三年的沈知意被重新叫回晚宴。顾沉舟、温雅、周特助和顾家长辈在公开场合集体失控，试图把她重新拖回豪门秩序。',
  tone: '低配豪门、当众发病、体面崩塌、旧情未死、女主清醒',
  cover: '/pixels/scene-gu-banquet-corridor.png',
};

export const initialStats: Stats = {
  budget: 100,
  buzz: 30,
  dignity: 70,
  control: 60,
};

export const tools: ToolDefinition[] = [
  {
    id: 'cut',
    name: '喊卡',
    icon: '✂',
    description: '打断当前表演，重新校准片场方向',
  },
  {
    id: 'rewrite',
    name: '改词',
    icon: '✎',
    description: '选中当前剧本文字，输入一个修改方向',
  },
  {
    id: 'chicken',
    name: '加鸡腿',
    icon: '▣',
    description: '花钱安抚当前最不稳的演员',
  },
  {
    id: 'demo',
    name: '导演示范',
    icon: '▤',
    description: '亲自示范这一段该怎么演',
  },
];

export const actors: Actor[] = [
  {
    id: 'lin-xiaoman',
    name: '林小满',
    label: '地下偶像退役成员',
    realIdentity: '前地下偶像成员，曾因被恶意解读的“偷吃”词条炎上退团。',
    hook: '她最懂镜头，也最怕镜头后的人把一句话听成另一个意思。',
    weirdValue: '镜头感强，表情管理好，能把被误解和强装体面演得很真。',
    uncontrolledPoint: '对双关、暧昧关系、可被截图传播的词句极度敏感。',
    suitableRoles: ['沈知意', '温雅'],
    lossDirection: '把短剧片场变成随时可能被误读的公关危机。',
    avatar: '/pixels/actor-real-lin-xiaoman.png',
    persuasionTemplate: '这场戏不是消费你，是需要你身上那种____之后还要站稳的体面。',
    defaultWord: '被误解',
  },
  {
    id: 'sun-manli',
    name: '孙曼丽',
    label: '美甲店老板娘',
    realIdentity: '小区美甲店老板娘，长期听客人聊感情八卦，也护着王娜娜。',
    hook: '她不是在演短剧，她是在给这段关系做诊断。',
    weirdValue: '极懂狗血关系里的心理动机，说出来的话像观众弹幕。',
    uncontrolledPoint: '会边演边分析人物关系，忍不住拆穿“这男的到底哪里不对”。',
    suitableRoles: ['顾家长辈', '温雅', '片场关系顾问'],
    lossDirection: '把剧情变成情感调解。',
    avatar: '/pixels/actor-real-sun-manli.png',
    persuasionTemplate: '这戏缺的不是演员，是一个真正懂____的人。',
    defaultWord: '关系',
  },
  {
    id: 'wang-nana',
    name: '王娜娜',
    label: '美甲店临时工 / 快手小主播预备役',
    realIdentity: '美甲店临时帮工，常拍快手对口型和变装，正被本地直播公会画饼。',
    hook: '她不是没机会，她只是太容易相信每一个说她能火的人。',
    weirdValue: '漂亮、不怯镜头、动作表现欲强，土、直、冲，但很有平台感。',
    uncontrolledPoint: '会把所有戏都演成“我今天必须让别人记住我”。',
    suitableRoles: ['沈知意', '温雅'],
    lossDirection: '把短剧拍成精神小妹狠狠爱，土但很带劲。',
    avatar: '/pixels/actor-real-wang-nana.png',
    persuasionTemplate: '你不是土，你是有一种____的镜头生命力。',
    defaultWord: '能火',
  },
  {
    id: 'zhang-jiahao',
    name: '张嘉豪',
    label: '夜场商务男模',
    realIdentity: '夜场商务演出男模，常接生日局、富婆局和酒吧主题夜。',
    hook: '他不是不会演深情，他只是会把所有深情都演成“姐姐今晚开心吗”。',
    weirdValue: '身体表现力强，镜头侵略感强，很会制造暧昧和压迫。',
    uncontrolledPoint: '会把霸总、危险感、深情都演成服务型暧昧营业。',
    suitableRoles: ['顾沉舟'],
    lossDirection: '把霸总戏演成夜场互动。',
    avatar: '/pixels/actor-real-zhang-jiahao.png',
    persuasionTemplate: '我找你来，不是因为你像夜场，是因为你身上有一种____的危险感。',
    defaultWord: '失控',
  },
  {
    id: 'qiu-peng',
    name: '邱鹏',
    label: '失业高中同学',
    realIdentity: '导演的高中同学，最近失业，朋友圈常发低谷期重启文案。',
    hook: '他不是来演戏的，他是来证明自己还没废。',
    weirdValue: '便宜、好说话、时间多，身上有真实失败感。',
    uncontrolledPoint: '台词碰到失败、没钱、被抛弃时，容易和现实重叠。',
    suitableRoles: ['顾沉舟', '周特助'],
    lossDirection: '把短剧里的落魄男主演成真实人生危机。',
    avatar: '/pixels/actor-real-qiu-peng.png',
    persuasionTemplate: '这个角色需要的不是演技，是你身上那种____之后还要撑住体面的劲儿。',
    defaultWord: '跌下来',
  },
  {
    id: 'guo-gang',
    name: '郭港',
    label: '夜班保安',
    realIdentity: '主角前司写字楼夜班保安，脸和身形很有压迫感。',
    hook: '长得像幕后大佬，其实只是困。',
    weirdValue: '不说话时特别像黑道、豪门管家、沉默父亲。',
    uncontrolledPoint: '极度怕麻烦，不想多说，不想多动，一开口神秘感掉一半。',
    suitableRoles: ['顾家长辈', '保镖', '沉默父亲'],
    lossDirection: '沉默很好用，但无法承受复杂表演。',
    avatar: '/pixels/actor-real-guo-gang.png',
    persuasionTemplate: '这场戏最缺的，是你这种不用说话也有____的气场。',
    defaultWord: '压迫',
  },
];

export const scriptRoles: ScriptRole[] = [
  {
    id: 'shen-zhiyi',
    name: '沈知意',
    function: '离开顾家三年的前妻，唯一试图保持正常的人。',
  },
  {
    id: 'gu-chenzhou',
    name: '顾沉舟',
    function: '顾家继承人，越想挽回越把事情搞得更糟。',
  },
  {
    id: 'wen-ya',
    name: '温雅',
    function: '体面现任，发现自己始终不是顾家真正认下的人。',
  },
  {
    id: 'zhou-assistant',
    name: '周特助 / 顾家长辈',
    function: '顾家秩序的荒唐出口，负责下跪、拱火和把顾家机器说出口。',
  },
];

const rolePreference: Record<string, string[]> = {
  'shen-zhiyi': ['lin-xiaoman', 'wang-nana', 'sun-manli'],
  'gu-chenzhou': ['zhang-jiahao', 'qiu-peng'],
  'wen-ya': ['lin-xiaoman', 'wang-nana', 'sun-manli'],
  'zhou-assistant': ['qiu-peng', 'guo-gang', 'sun-manli'],
};

export function assignCasting(selectedActors: Actor[]): Casting[] {
  if (selectedActors.length < scriptRoles.length) return [];

  const remaining = [...selectedActors];
  return scriptRoles.map((role) => {
    const preferred = rolePreference[role.id] || [];
    const matchIndex = remaining.findIndex((actor) => preferred.includes(actor.id));
    const actor = remaining.splice(matchIndex >= 0 ? matchIndex : 0, 1)[0];

    return {
      scriptRoleId: role.id,
      scriptRoleName: role.name,
      actorId: actor.id,
      actorName: actor.name,
    };
  });
}

export const scriptSkeleton: ScriptSkeletonAct[] = [
  {
    actId: 'act_01',
    title: '顾家晚宴外廊羞辱',
    scene: '顾家晚宴外廊，灯火通明，两侧站着顾家亲戚和宾客，像在等人，也像在等笑话。',
    mustHappen: '沈知意被顾家亲戚和宾客围观羞辱，顾沉舟出场要求她进去。',
    bombPoint: '顾家人一边把她当外人，一边又默认她必须回到顾家秩序里。',
    requiredOutcome: '沈知意意识到今晚不是普通见面，而是顾家公开设局。',
    targetLineCount: { min: 18, max: 22 },
    beats: [
      {
        beatId: 'act_01_b01',
        beatType: 'shot',
        referenceText: '顾家晚宴外廊灯火很满，宾客和亲戚站在两侧，空气像提前排好的一场审判。',
        actionCue: '镜头从水晶灯扫到沈知意停下的脚步。',
        innerCue: '沈知意一进来就知道这不是一顿好饭。',
        riskTag: '围观压迫',
        mustKeep: true,
      },
      {
        beatId: 'act_01_b02',
        beatType: 'dialogue',
        speaker: '顾家长辈',
        referenceText: '还知道回来。顾家这些年，倒是第一次为了一个外人这么热闹。',
        riskTag: '长辈羞辱台词',
        mustKeep: true,
      },
      {
        beatId: 'act_01_b03',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '不是你们叫我来的么。现在我来了，又摆这副脸给谁看？',
        innerCue: '她不是怕，是在确认顾家到底想把她放到什么位置。',
        riskTag: '女主反击开场',
        mustKeep: true,
      },
      {
        beatId: 'act_01_b04',
        beatType: 'action',
        speaker: '顾沉舟',
        referenceText: '顾沉舟从人群里走出来，盯着她，说：知意，跟我进去。',
        actionCue: '他不是邀请，是宣布。',
        riskTag: '霸总压迫感',
        mustKeep: true,
      },
      {
        beatId: 'act_01_b05',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '顾总是不是忘了，我三年前就不是顾家的人了。',
        innerCue: '她主动把“前妻”身份切断。',
        riskTag: '身份切割',
        mustKeep: true,
      },
      {
        beatId: 'act_01_b06',
        beatType: 'dialogue',
        speaker: '温雅',
        referenceText: '是不是顾家的人，不是你一句话说了算。今晚能站在这里的人，才算。',
        innerCue: '温雅表面体面，实际在宣示席位。',
        riskTag: '现任挑衅',
        mustKeep: true,
      },
      {
        beatId: 'act_01_b07',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '那你站得挺稳的。',
        actionCue: '温雅笑意僵住。',
        riskTag: '短句打脸',
        mustKeep: true,
      },
      {
        beatId: 'act_01_b08',
        beatType: 'turning_point',
        speaker: '顾沉舟',
        referenceText: '我最后说一遍，跟我进去。沈知意回：我要是不呢？顾沉舟说：由不得你。',
        actionCue: '顾沉舟开始越过正常沟通边界。',
        riskTag: '强制带入下一幕',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_02',
    title: '顾沉舟公开越线',
    scene: '晚宴外廊中央，宾客距离很近，所有人的目光都卡在顾沉舟和沈知意身上。',
    mustHappen: '顾沉舟试图用强势方式把沈知意拖回顾家。',
    bombPoint: '原剧本是当众强吻，素人演员会对动作边界、人物逻辑和体面感产生抗拒。',
    requiredOutcome: '顾沉舟公开失控，温雅被刺激，沈知意被冒犯。',
    targetLineCount: { min: 20, max: 24 },
    beats: [
      {
        beatId: 'act_02_b01',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '三年前你让我滚的时候，也说过这句。',
        innerCue: '她把顾沉舟现在的“挽回”和当年的驱逐放在一起。',
        riskTag: '旧伤翻出',
        mustKeep: true,
      },
      {
        beatId: 'act_02_b02',
        beatType: 'action',
        speaker: '顾沉舟',
        referenceText: '顾沉舟眼神一沉，突然上前，一把拽住她手腕。',
        actionCue: '动作要明显越线，但可以根据工具干预改成拦路、抓袖口或逼近。',
        riskTag: '肢体边界',
        mustKeep: true,
      },
      {
        beatId: 'act_02_b03',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你干什么——',
        innerCue: '她的第一反应是被冒犯，不是心动。',
        riskTag: '女主抗拒',
        mustKeep: true,
      },
      {
        beatId: 'act_02_b04',
        beatType: 'action',
        speaker: '顾沉舟',
        referenceText: '顾沉舟直接将她拽到面前，当众强吻。',
        actionCue: '镜头贴近两人的距离变化，动作可以根据现场状态处理成借位、错位、停在半步外或被及时打断。',
        riskTag: '必炸动作',
        mustKeep: true,
      },
      {
        beatId: 'act_02_b05',
        beatType: 'shot',
        referenceText: '全场安静，几秒后沈知意猛地推开他，抬手就是一巴掌。',
        actionCue: '片场如果前面改掉强吻，这里也必须跟着改成对应反击。',
        riskTag: '强反击动作',
        mustKeep: true,
      },
      {
        beatId: 'act_02_b06',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '顾沉舟，你有病吧？！',
        riskTag: '价值观撞击',
        mustKeep: true,
      },
      {
        beatId: 'act_02_b07',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '对，我有病。从你签字离婚那天起，我就没正常过。',
        innerCue: '他把后悔说成病，把失控包装成深情。',
        riskTag: '疯批深情',
        mustKeep: true,
      },
      {
        beatId: 'act_02_b08',
        beatType: 'inner',
        speaker: '温雅',
        referenceText: '温雅站在旁边，笑了一下，但眼神已经不对了。',
        innerCue: '她意识到自己站在顾沉舟身边，也未必是被承认的人。',
        riskTag: '女二被点燃',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_03',
    title: '这一口是你欠顾家的',
    scene: '同一条外廊，强行越线后的寂静还没有散，顾家人和宾客都在等下一句怎么收场。',
    mustHappen: '顾沉舟说出一句把沈知意重新绑定顾家的冒犯台词。',
    bombPoint: '“这一口，是你欠顾家的”太疯也太脏，演员可能要求改。',
    requiredOutcome: '顾沉舟的挽回被证明仍然裹着顾家的控制和债务逻辑。',
    targetLineCount: { min: 18, max: 22 },
    beats: [
      {
        beatId: 'act_03_b01',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你发疯别拉着我。',
        innerCue: '她拒绝把他的失控理解成爱情。',
        riskTag: '女主清醒',
        mustKeep: true,
      },
      {
        beatId: 'act_03_b02',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '这一口，是你欠顾家的。',
        actionCue: '镜头落在众人的反应上，让刚才那场难堪变成所有人都无法假装没看见的空气。',
        riskTag: '台词说不出口',
        mustKeep: true,
      },
      {
        beatId: 'act_03_b03',
        beatType: 'shot',
        referenceText: '全场直接死寂，连顾家长辈都愣住了一秒。',
        riskTag: '空气冻结',
        mustKeep: true,
      },
      {
        beatId: 'act_03_b04',
        beatType: 'inner',
        speaker: '沈知意',
        referenceText: '沈知意像是被这句话雷到，气得都笑了。',
        innerCue: '她不是被打动，是确认顾家仍然把她当债务。',
        riskTag: '怒极反笑',
        mustKeep: true,
      },
      {
        beatId: 'act_03_b05',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '我欠顾家？你们顾家是有脸说这种话的？',
        riskTag: '女主打脸',
        mustKeep: true,
      },
      {
        beatId: 'act_03_b06',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '我就是要让所有人看清楚——顾家认的人，从来都只有你。',
        innerCue: '他以为这是给名分，实际更像公开占有。',
        riskTag: '深情变控制',
        mustKeep: true,
      },
      {
        beatId: 'act_03_b07',
        beatType: 'dialogue',
        speaker: '顾家长辈',
        referenceText: '疯了……真疯了……',
        riskTag: '顾家也被吓到',
        mustKeep: false,
      },
      {
        beatId: 'act_03_b08',
        beatType: 'turning_point',
        speaker: '温雅',
        referenceText: '只有她？',
        actionCue: '温雅从旁观者变成下一幕的主动失控者。',
        riskTag: '女二反击起点',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_04',
    title: '温雅失控反击',
    scene: '外廊人群中央，温雅从顾沉舟身侧走出来，体面表情开始裂开。',
    mustHappen: '温雅被顾沉舟对沈知意的偏向刺激，当众失去体面。',
    bombPoint: '原剧本是温雅反强吻顾沉舟，动作和动机会让演员炸锅。',
    requiredOutcome: '温雅不再只是体面现任，而成为修罗场第二个发病的人。',
    targetLineCount: { min: 20, max: 24 },
    beats: [
      {
        beatId: 'act_04_b01',
        beatType: 'action',
        speaker: '温雅',
        referenceText: '温雅一步一步走过去，猛地拽住顾沉舟领带，把人拉下来。',
        actionCue: '动作要体现“我要把你刚才给她的东西抢回来”。',
        riskTag: '女二动作越线',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b02',
        beatType: 'action',
        speaker: '温雅',
        referenceText: '温雅当着沈知意的面强吻了顾沉舟。',
        actionCue: '可根据前文补丁改成近距离逼视、贴脸宣示、抓领带逼问。',
        riskTag: '必炸动作',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b03',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你们顾家平时吃饭都这么演吗？',
        riskTag: '女主吐槽降维',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b04',
        beatType: 'action',
        speaker: '顾沉舟',
        referenceText: '顾沉舟立刻把温雅推开：温雅，你够了！',
        riskTag: '男主把女二推到对立面',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b05',
        beatType: 'dialogue',
        speaker: '温雅',
        referenceText: '我够了？顾沉舟，你当着我的面吻她，现在还说我够了？',
        innerCue: '她终于把体面话撕开，说出自己被当空气的羞辱。',
        riskTag: '现任崩盘',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b06',
        beatType: 'dialogue',
        speaker: '温雅',
        referenceText: '你可以拿她刺激我，但你不能拿她赢我。',
        innerCue: '她不是单纯吃醋，是输不起位置。',
        riskTag: '抽象短剧台词',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b07',
        beatType: 'dialogue',
        speaker: '温雅',
        referenceText: '如果不是你，今晚站在这里的人就是我！',
        riskTag: '女二地位焦虑',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b08',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '那你站啊。我又没跟你抢。',
        innerCue: '沈知意拒绝进入雌竞逻辑。',
        riskTag: '女主拒绝陪演',
        mustKeep: true,
      },
      {
        beatId: 'act_04_b09',
        beatType: 'turning_point',
        speaker: '顾沉舟',
        referenceText: '都给我闭嘴。',
        actionCue: '男主试图重新控场，但已经压不住顾家集体发病。',
        riskTag: '控场失败',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_05',
    title: '顾家选女主人',
    scene: '晚宴厅入口被吵声吸引，顾家长辈终于从体面外壳里伸手干预。',
    mustHappen: '顾家长辈把私人修罗场升级成顾家秩序问题。',
    bombPoint: '“今晚谁能留下，谁就是顾家的女主人”封建又拱火，演员可能说不出口。',
    requiredOutcome: '沈知意确认顾家从头到尾仍把她当成一个位置。',
    targetLineCount: { min: 18, max: 22 },
    beats: [
      {
        beatId: 'act_05_b01',
        beatType: 'shot',
        referenceText: '一位顾家长辈终于忍不住开口，声音不大，却足够让所有人听见。',
        actionCue: '镜头从年轻人的修罗场切到顾家秩序本身。',
        riskTag: '长辈入场',
        mustKeep: true,
      },
      {
        beatId: 'act_05_b02',
        beatType: 'dialogue',
        speaker: '顾家长辈',
        referenceText: '今晚谁能留下，谁就是顾家的女主人。',
        innerCue: '长辈不认为这是侮辱，而认为这是给位置。',
        riskTag: '封建台词',
        mustKeep: true,
      },
      {
        beatId: 'act_05_b03',
        beatType: 'inner',
        speaker: '温雅',
        referenceText: '温雅呼吸都急了。',
        innerCue: '她听见“女主人”三个字，第一反应是自己终于被放上秤，但也可能输。',
        riskTag: '女二被拱火',
        mustKeep: true,
      },
      {
        beatId: 'act_05_b04',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你们顾家现在连人都要这么选？',
        innerCue: '她确认自己不是被邀请，是被公开估价。',
        riskTag: '女主识破机制',
        mustKeep: true,
      },
      {
        beatId: 'act_05_b05',
        beatType: 'dialogue',
        speaker: '顾家长辈',
        referenceText: '顾家的体面不能没人撑，谁能撑住，谁就留下。',
        riskTag: '顾家机器说人话',
        mustKeep: false,
      },
      {
        beatId: 'act_05_b06',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '够了，这不是你们能决定的事。',
        innerCue: '他想护沈知意，但仍然默认她和顾家的关系可以被讨论。',
        riskTag: '男主护人失败',
        mustKeep: true,
      },
      {
        beatId: 'act_05_b07',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你现在拦他们，是怕他们羞辱我，还是怕他们把你的心思说太明白？',
        riskTag: '女主剖开男主',
        mustKeep: true,
      },
      {
        beatId: 'act_05_b08',
        beatType: 'turning_point',
        referenceText: '人群外传来急促脚步声，周特助冲进来。',
        actionCue: '下一幕从长辈封建，升级成助理殉道式下跪。',
        riskTag: '周特助冲场',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_06',
    title: '周特助下跪',
    scene: '晚宴厅边缘，周特助从人群后冲出来，像比顾沉舟本人更急。',
    mustHappen: '周特助冲出来跪求沈知意回顾家。',
    bombPoint: '总助突然下跪动作过满，演员会问“我真的要跪吗”。',
    requiredOutcome: '顾家集体发病具象化，周特助比主子还投入。',
    targetLineCount: { min: 18, max: 22 },
    beats: [
      {
        beatId: 'act_06_b01',
        beatType: 'action',
        speaker: '周特助',
        referenceText: '周特助突然冲上来，眼圈发红，扑通一声跪下。',
        actionCue: '镜头压住周特助身体下沉的瞬间，动作可以根据现场状态处理成半跪、扶桌、深鞠躬或跪到一半被拦。',
        riskTag: '必炸动作',
        mustKeep: true,
      },
      {
        beatId: 'act_06_b02',
        beatType: 'dialogue',
        speaker: '周特助',
        referenceText: '顾总！别闹了！老爷子撑着一口气，就是想见少夫人回家！',
        innerCue: '他像顾家机器里最真诚也最荒唐的零件。',
        riskTag: '总助过度投入',
        mustKeep: true,
      },
      {
        beatId: 'act_06_b03',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你叫谁少夫人？',
        riskTag: '称呼反感',
        mustKeep: true,
      },
      {
        beatId: 'act_06_b04',
        beatType: 'dialogue',
        speaker: '周特助',
        referenceText: '少夫人，顾家不能没有您！',
        riskTag: '台词说不出口',
        mustKeep: true,
      },
      {
        beatId: 'act_06_b05',
        beatType: 'dialogue',
        speaker: '周特助',
        referenceText: '这三年顾总没睡过一个安稳觉，老爷也没真正高兴过一天！',
        innerCue: '他把顾家的所有痛苦都压到沈知意该回去这件事上。',
        riskTag: '道德绑架',
        mustKeep: true,
      },
      {
        beatId: 'act_06_b06',
        beatType: 'shot',
        referenceText: '全场没人敢接话，顾沉舟僵住，温雅脸色越来越白。',
        riskTag: '全员尴尬',
        mustKeep: true,
      },
      {
        beatId: 'act_06_b07',
        beatType: 'inner',
        speaker: '沈知意',
        referenceText: '沈知意看着跪在地上的周特助，像终于看懂顾家这套秩序有多荒唐。',
        riskTag: '女主看清顾家',
        mustKeep: true,
      },
      {
        beatId: 'act_06_b08',
        beatType: 'turning_point',
        speaker: '周特助',
        referenceText: '周特助越说越激动，彻底豁出去了。',
        actionCue: '铺垫下一幕最炸台词。',
        riskTag: '失控升级',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_07',
    title: '只有您和温小姐的嘴',
    scene: '顾家晚宴现场空气冻结，周特助仍跪着，所有人已经不确定这场戏还能不能拍下去。',
    mustHappen: '周特助说出极炸、极尴尬的忠心台词。',
    bombPoint: '“顾总三年碰过的女人，只有您和温小姐的嘴”会让全场沉默。',
    requiredOutcome: '片场空气冻结，顾家荒唐忠心被推到顶点。',
    targetLineCount: { min: 18, max: 22 },
    beats: [
      {
        beatId: 'act_07_b01',
        beatType: 'dialogue',
        speaker: '周特助',
        referenceText: '少夫人，顾总这三年碰过的女人，只有您和温小姐的嘴！',
        actionCue: '镜头扫过顾沉舟和温雅，空气里只剩下说不出口的尴尬。',
        riskTag: '最炸台词',
        mustKeep: true,
      },
      {
        beatId: 'act_07_b02',
        beatType: 'shot',
        referenceText: '全场彻底安静，不是震惊，是那种“这也能说”的空白。',
        riskTag: '空气冻结',
        mustKeep: true,
      },
      {
        beatId: 'act_07_b03',
        beatType: 'inner',
        speaker: '顾沉舟',
        referenceText: '顾沉舟都僵了一瞬。',
        innerCue: '他第一次发现自己的失控被助理说成了顾家公文。',
        riskTag: '男主尴尬',
        mustKeep: true,
      },
      {
        beatId: 'act_07_b04',
        beatType: 'dialogue',
        speaker: '温雅',
        referenceText: '周特助，你疯了吗？！',
        innerCue: '温雅被公开放在和沈知意同一张荒唐表格上。',
        riskTag: '女二破防',
        mustKeep: true,
      },
      {
        beatId: 'act_07_b05',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '……你们顾家，是真没一个正常人了。',
        riskTag: '女主总结疯感',
        mustKeep: true,
      },
      {
        beatId: 'act_07_b06',
        beatType: 'dialogue',
        speaker: '周特助',
        referenceText: '少夫人，您要是不回去，顾家今晚就真的散了！',
        riskTag: '道德绑架加码',
        mustKeep: true,
      },
      {
        beatId: 'act_07_b07',
        beatType: 'dialogue',
        speaker: '温雅',
        referenceText: '够了！我到底算什么？！',
        innerCue: '她终于承认自己害怕的是没有名分。',
        riskTag: '女二崩溃',
        mustKeep: true,
      },
      {
        beatId: 'act_07_b08',
        beatType: 'dialogue',
        speaker: '周特助',
        referenceText: '温小姐，您不是顾家的人。可少夫人，是老爷亲口认下的。',
        riskTag: '顾家认人机制',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_08',
    title: '沈知意全员审判',
    scene: '晚宴厅中央，所有人的失控都堆在沈知意面前，她终于不再只接招。',
    mustHappen: '沈知意把顾沉舟、温雅、周特助和顾家长辈全部剖开。',
    bombPoint: '女主长篇审判爽但难演，演员可能想从总结陈词改成直接骂人。',
    requiredOutcome: '沈知意说清自己不是回来被选，而是拒绝再次被顾家定义。',
    targetLineCount: { min: 22, max: 26 },
    beats: [
      {
        beatId: 'act_08_b01',
        beatType: 'shot',
        referenceText: '沈知意看着眼前跪着的、疯着的、哭着的、盯着她的这一群人，彻底冷下来。',
        innerCue: '她不是情绪崩溃，而是进入审判状态。',
        riskTag: '女主开大前静默',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b02',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '一个当众强吻，一个当众发疯，一个当众下跪，一个当众选女主人。',
        actionCue: '沈知意把今晚发生过的难堪一件件摆回桌面，语速不快，但每句都像落锤。',
        riskTag: '总结前文事故',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b03',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你们顾家今晚这出戏，真够热闹的。',
        riskTag: '冷讽收束',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b04',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '知意，跟我回去。只要你点头，顾家的一切都是你的。',
        innerCue: '他仍然以为给出顾家资源就是补偿。',
        riskTag: '男主迟到补偿',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b05',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '我现在看起来，很像缺你们顾家这口饭吗？',
        riskTag: '女主拒绝施舍',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b06',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '你可以不要我。但你不能不要本来就属于你的东西。',
        riskTag: '占有包装成归还',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b07',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你现在是想让我回顾家，还是想让我回去，替你们所有人收拾这场烂戏？',
        riskTag: '女主剖核心',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b08',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '你当众吻我，是想证明你后悔了。她当众吻你，是想证明她没输。你助理跪下来求我，是想证明顾家离不开我。',
        actionCue: '她的目光从顾家人脸上扫过，把这场晚宴里发生过的荒唐一笔一笔还回去。',
        riskTag: '长台词难演',
        mustKeep: true,
      },
      {
        beatId: 'act_08_b09',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '可你们从头到尾，没有一个人问过——我还想不想踏进这个门。',
        riskTag: '主题句',
        mustKeep: true,
      },
    ],
  },
  {
    actId: 'act_09',
    title: '真够下贱的',
    scene: '顾家晚宴门口，沈知意已经转身，顾沉舟最后一次试图把她留住。',
    mustHappen: '沈知意留下最后一刀，转身离开，黑屏收尾。',
    bombPoint: '“你们顾家求人回去的方式，真够下贱的”太狠，演员可能想收。',
    requiredOutcome: '第一集以沈知意离开和顾家继续失控收尾。',
    targetLineCount: { min: 18, max: 22 },
    beats: [
      {
        beatId: 'act_09_b01',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '那你说。只要你开口，我今天就把整个顾家掀了，也把你请回去。',
        innerCue: '他终于从命令变成乞求，但表达仍然像控制。',
        riskTag: '男主最后挽回',
        mustKeep: true,
      },
      {
        beatId: 'act_09_b02',
        beatType: 'shot',
        referenceText: '沈知意冷笑一声，停在门口，没有回头。',
        riskTag: '最后一刀前停顿',
        mustKeep: true,
      },
      {
        beatId: 'act_09_b03',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '顾总。你们顾家求人回去的方式，真够下贱的。',
        actionCue: '沈知意停在门口，声音不高，却把顾家的求人方式钉在原地。',
        riskTag: '终场狠台词',
        mustKeep: true,
      },
      {
        beatId: 'act_09_b04',
        beatType: 'action',
        speaker: '沈知意',
        referenceText: '她转身就走。',
        actionCue: '镜头跟住沈知意离开的背影，顾家的人留在原地，没有人再拦得住她。',
        riskTag: '女主夺回行动权',
        mustKeep: true,
      },
      {
        beatId: 'act_09_b05',
        beatType: 'dialogue',
        speaker: '顾沉舟',
        referenceText: '沈知意！你今天不回顾家，明天他们也会来请你！',
        riskTag: '男主控制余波',
        mustKeep: true,
      },
      {
        beatId: 'act_09_b06',
        beatType: 'dialogue',
        speaker: '沈知意',
        referenceText: '那就让他们排队。',
        riskTag: '爽感收尾',
        mustKeep: true,
      },
      {
        beatId: 'act_09_b07',
        beatType: 'shot',
        referenceText: '顾家人留在灯火里，体面终于彻底碎在地上。',
        innerCue: '第一集不是爱情和解，而是顾家秩序第一次被她公开拒绝。',
        riskTag: '顾家崩塌画面',
        mustKeep: true,
      },
      {
        beatId: 'act_09_b08',
        beatType: 'turning_point',
        referenceText: '黑屏。',
        actionCue: '结尾要像短剧第一集钩子，留下顾家明天还会继续发疯的余波。',
        riskTag: '第一集钩子',
        mustKeep: true,
      },
    ],
  },
];

export const actBackgrounds: Record<string, string> = {
  act_01: '/pixels/scene-gu-banquet-corridor.png',
  act_02: '/pixels/scene-gu-side-corridor.png',
  act_03: '/pixels/scene-gu-side-corridor.png',
  act_04: '/pixels/scene-gu-banquet-hall.png',
  act_05: '/pixels/scene-gu-mansion-room.png',
  act_06: '/pixels/scene-gu-mansion-room.png',
  act_07: '/pixels/scene-gu-mansion-room.png',
  act_08: '/pixels/scene-gu-side-corridor.png',
  act_09: '/pixels/scene-gu-night-exit.png',
};

export const rolePortraits: Record<string, string> = {
  'shen-zhiyi': '/pixels/role-shen-zhiyi.png',
  'gu-chenzhou': '/pixels/role-gu-chenzhou.png',
  'wen-ya': '/pixels/role-wen-ya.png',
  'zhou-assistant': '/pixels/role-zhou-assistant.png',
};
